apiVersion: v1
kind: Service
metadata:
  name: k8s-web-hello
spec:
  type: LoadBalancer
  selector:
    app: k8s-web-hello
    version: 1.0.0
  ports:
  - port: 3030
    targetPort: 3000
    protocol: "TCP"
